name: GlassMail Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    name: Analyze, Test and Build
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./flutter_app

    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"
      - uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11479570

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'any'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build iOS IPA
        run: flutter build ios --release --no-codesign
